/* ProjectorApp — données du portfolio
   33 projets GitHub de nouhailler, répartis en 7 collections.
   Les fiches ajoutées (synchro GitHub ou README collé) sont fusionnées
   par-dessus ce socle et persistées dans localStorage.

   Modèle d'une fiche :
     id, name, repo, branch, private, cat, kind, year, tagline, pitch,
     features: [string], tech: [string], shots: [url],
     featured?  : bool — mis en avant sur l'accueil
     live?      : URL de l'app déployée (ex. https://x.netlify.app) — absent si non déployé
     userAdded? : bool, source? : "ai"|"ai-refresh"|"fallback", baseline? : string */

export const OWNER = "nouhailler";

export const CATEGORIES = [
  { id: "sante",    label: "Santé & soin",        accent: "#5C7A52", note: "Comprendre son corps, se soigner, intervenir vite." },
  { id: "maison",   label: "Maison & quotidien",  accent: "#A8623C", note: "Le potager, la cuisine, la famille, la sortie du soir." },
  { id: "data",     label: "Météo & finance",     accent: "#3F6076", note: "Lire le ciel et les marchés, sans clé API ni compte." },
  { id: "medias",   label: "Médias & lecture",    accent: "#7A4B63", note: "Lire, écouter, regarder, convertir — à sa façon." },
  { id: "creation", label: "Création & écriture", accent: "#977B2C", note: "Dessiner, noter, éditer, tenir un journal." },
  { id: "systeme",  label: "Système & réseau",    accent: "#2E6B63", note: "Outils d'admin Linux avec une vraie interface." },
  { id: "langues",  label: "Langues & IA",        accent: "#9A4F3C", note: "Apprendre, traduire, vérifier, relier — assisté par IA." },
];

export const PROJECTS = [
  // ───────────────────────── Santé & soin
  {
    id: "nutritor", name: "Nutritor", repo: "nutritor", branch: "master", private: false,
    cat: "sante", kind: "Mobile · Web", year: "2025", live: "https://nutritor.netlify.app",
    tagline: "Compagnon de connaissance nutritionnelle pour estomacs sensibles.",
    pitch: "Pas une appli de régime, mais un compagnon pour comprendre ce que l'on mange. Base CIQUAL (3 167 aliments), Open Food Facts, scanner code-barres, timeline physiologique interactive et mémoire digestive qui croise 21 jours de repas et de symptômes pour révéler vos intolérances. L'IA — optionnelle, via OpenRouter, Ollama, Claude ou OpenAI — enrichit les fiches et génère des repas adaptés au profil FODMAP.",
    features: [
      "Journal nutritionnel : anneau kcal + répartition P/G/L en direct",
      "Timeline physiologique interactive (glycémie, FODMAP, satiété)",
      "Scanner code-barres + bases CIQUAL & Open Food Facts",
      "Mémoire digestive : corrélations aliment → symptômes sur 30 jours",
      "Enrichissement de fiches & générateur de repas par IA",
    ],
    tech: ["React Native", "Expo", "TypeScript", "IA", "CIQUAL"],
    shots: ["assets/shots/nutritor-journal.png", "assets/shots/nutritor-stats.png", "assets/shots/nutritor-profil.png"],
    featured: true,
  },
  {
    id: "medicor", name: "Medicor", repo: "Medicor", branch: "main", private: true,
    cat: "sante", kind: "Web · PWA", year: "2025", live: "https://medikor.netlify.app",
    tagline: "Médecine douce générée par IA : pathologies, huiles, phyto.",
    pitch: "Une PWA mobile-first dédiée aux thérapies naturelles : 2 102 pathologies, 306 huiles essentielles, phytothérapie, nutrition, remèdes maison et navigation par zone anatomique. Chaque fiche est générée par IA (Ollama en local ou OpenRouter), adossée à la base officielle BDPM de 13 592 médicaments. Design « Nature & Serenity » — sauge, terracotta, Newsreader.",
    features: [
      "2 102 pathologies & 306 huiles essentielles référencées",
      "Génération de fiches par IA (Ollama local ou OpenRouter)",
      "Navigation par zone anatomique (16 zones du corps)",
      "Base BDPM officielle : 13 592 médicaments (ANSM)",
      "Installable en PWA, mode hors-ligne",
    ],
    tech: ["React", "Vite", "PWA", "IA", "Tailwind"],
    shots: ["assets/shots/medicor-home.png", "assets/shots/medicor-demo.png"],
    featured: true,
  },
  {
    id: "urgentor", name: "Urgentor", repo: "urgentor", branch: "main", private: true,
    cat: "sante", kind: "Web · PWA", year: "2025", live: "https://urgentor.netlify.app",
    tagline: "Premiers secours fiables, accessibles hors-ligne.",
    pitch: "Des fiches de premiers secours rapides et conformes aux référentiels officiels : secours à personne, risque chimique, NRBC, incendie et évacuation. Pensé pour fonctionner hors-ligne, avec synthèse vocale et un générateur de fiches par IA (OpenRouter).",
    features: [
      "Fiches secours à personne, chimique, NRBC, incendie/évacuation",
      "Fonctionne entièrement hors-ligne (PWA)",
      "Synthèse vocale des consignes",
      "Conforme aux référentiels officiels",
      "Générateur de fiches par IA (OpenRouter)",
    ],
    tech: ["React", "Vite", "PWA", "IA", "Voix"],
    shots: [],
  },

  // ───────────────────────── Maison & quotidien
  {
    id: "jardinator", name: "Jardinator", repo: "jardinator", branch: "main", private: false,
    cat: "maison", kind: "Bureau Linux · Web", year: "2025", live: "https://jardinator.netlify.app",
    tagline: "Planificateur de potager : semis, associations, calendrier.",
    pitch: "Un planificateur de potager complet : calendrier de semis, associations de cultures, distances de plantation, diagnostic et conseils, sur une base de données de centaines de légumes et variétés. Décliné en application Linux (PyQt) et en version web installable (PWA).",
    features: [
      "Calendrier de semis et de récolte",
      "Associations de cultures & distances de plantation",
      "Diagnostic et conseils par plante",
      "Base de centaines de légumes et variétés",
      "Versions Linux (PyQt) et web (PWA)",
    ],
    tech: ["Python", "PyQt", "React", "PWA"],
    shots: ["assets/shots/jardinator-desktop.png", "assets/shots/jardinator-mobile.png"],
    featured: true,
  },
  {
    id: "recettor", name: "Recettor", repo: "recettor", branch: "main", private: true,
    cat: "maison", kind: "Bureau Linux", year: "2024",
    tagline: "Recettes, frigo et saisonnalité, avec suggestions Ollama.",
    pitch: "Un gestionnaire de recettes desktop : recherche par ingrédients du frigo, vue saisonnière, listes de courses et favoris. Les suggestions de recettes s'appuient sur Ollama, en local.",
    features: [
      "Recherche de recettes par ingrédients du frigo",
      "Vue saisonnière des recettes",
      "Listes de courses et favoris",
      "Suggestions de recettes via Ollama (local)",
    ],
    tech: ["Python", "PyQt", "Ollama"],
    shots: [],
  },
  {
    id: "recettor-web", name: "Recettor Web", repo: "recettor-web", branch: "main", private: true,
    cat: "maison", kind: "Web", year: "2025", live: "https://recettor.netlify.app",
    tagline: "La déclinaison web de Recettor (React + Vite).",
    pitch: "Version web de Recettor pour consulter et créer des recettes depuis le navigateur, déployée sur Netlify, avec génération assistée par OpenRouter.",
    features: [
      "Consultation et création de recettes au navigateur",
      "Génération assistée par OpenRouter",
      "Déployé sur Netlify",
    ],
    tech: ["React", "Vite", "OpenRouter"],
    shots: [],
  },
  {
    id: "theatror", name: "Theatror", repo: "theatror", branch: "main", private: false,
    cat: "maison", kind: "Web · PWA", year: "2025", live: "https://theatror.netlify.app",
    tagline: "Les pièces de théâtre à Paris, cette semaine.",
    pitch: "Une app web légère qui liste les pièces de théâtre jouées à Paris cette semaine — recherche, filtres et favoris. Les données viennent de l'Open Data de la Ville de Paris ; installable en PWA.",
    features: [
      "Pièces jouées à Paris cette semaine",
      "Recherche, filtres et favoris",
      "Données Open Data de la Ville de Paris",
      "Installable en PWA",
    ],
    tech: ["React", "Vite", "PWA", "Open Data"],
    shots: [],
  },
  {
    id: "genealogor", name: "Genealogor", repo: "genealogor", branch: "master", private: false,
    cat: "maison", kind: "Web · PWA", year: "2025", live: "https://genealogor.netlify.app",
    tagline: "Arbre généalogique interactif avec laboratoire IA.",
    pitch: "Une application de généalogie riche : arbres ascendants et descendants, vue sablier, implexe, carte géographique des lieux, timeline et statistiques. Coffre chiffré, pièces jointes, et un laboratoire IA pour enrichir biographies et hypothèses.",
    features: [
      "Arbres ascendants, descendants, sablier, implexe",
      "Carte géographique des lieux & timeline",
      "Statistiques et comparaison de profils",
      "Coffre chiffré et pièces jointes",
      "Laboratoire IA : biographies et hypothèses",
    ],
    tech: ["React", "TypeScript", "IA", "Cartographie"],
    shots: [],
  },

  // ───────────────────────── Météo & finance
  {
    id: "meteor", name: "Meteor", repo: "meteor", branch: "main", private: true,
    cat: "data", kind: "Web · Desktop", year: "2025", live: "https://meteo-r.netlify.app",
    tagline: "Tableau de bord météo open-source, sans clé API.",
    pitch: "Un tableau de bord météo en React + Vite, 100 % open data via Open-Meteo : prévisions 7 jours, carte interactive avec overlays, qualité de l'air, historique jusqu'à 90 jours et export CSV. Aucun compte, aucune clé API, aucune télémétrie.",
    features: [
      "Prévisions 7 jours, horaires et alertes automatiques",
      "Carte interactive avec overlays (pluie, vent, température)",
      "Qualité de l'air : 6 polluants + indice IQA",
      "Historique jusqu'à 90 jours + export CSV",
      "100 % open data, sans clé API ni compte",
    ],
    tech: ["React", "Vite", "Chart.js", "Leaflet"],
    shots: ["assets/shots/meteor-dash.png", "assets/shots/meteor-air.png"],
    featured: true,
  },
  {
    id: "weathor", name: "Weathor", repo: "weathor", branch: "main", private: true,
    cat: "data", kind: "Bureau Linux", year: "2025", live: "https://weathor.netlify.app",
    tagline: "App météo GTK4, prévisions 7 jours sans clé API.",
    pitch: "Une application météo native GTK4 propulsée par Open-Meteo : prévisions 7 jours, indice UV, pression, humidité, rafales de vent. Architecture MVC propre, tests inclus, aucune clé API requise.",
    features: [
      "Prévisions 7 jours via Open-Meteo",
      "Indice UV, pression, humidité, rafales",
      "Interface native GTK4",
      "Architecture MVC testée",
      "Aucune clé API requise",
    ],
    tech: ["Python", "GTK4", "Open-Meteo"],
    shots: [],
  },
  {
    id: "financor", name: "Financor", repo: "financor", branch: "main", private: true,
    cat: "data", kind: "Web", year: "2025",
    tagline: "Suivi boursier en temps réel, épuré et pro.",
    pitch: "Une app web de suivi boursier en temps réel : tableau de bord, watchlist, portefeuille, alertes et actualités. Le backend agrège plusieurs fournisseurs (Finnhub, Alpha Vantage, FMP, Twelve Data) avec bascule transparente en cas de panne.",
    features: [
      "Tableau de bord boursier en temps réel",
      "Watchlist, portefeuille et alertes",
      "Fil d'actualités marché",
      "Backend multi-fournisseurs avec bascule automatique",
    ],
    tech: ["React", "Vite", "Tailwind", "Python"],
    shots: [],
  },

  // ───────────────────────── Médias & lecture
  {
    id: "karatagor", name: "KaraTagor", repo: "KaraTagor", branch: "main", private: false,
    cat: "medias", kind: "Bureau Linux · Android", year: "2025", live: "https://karatagor.netlify.app",
    tagline: "Lecteur karaoké MP3 + éditeur de tags ID3.",
    pitch: "Une app desktop Python : lecture de MP3 en mode karaoké avec paroles synchronisées, identification automatique et édition des tags ID3v2, gestion de playlists avec explorateur de fichiers. Déclinée aussi en build Android via Capacitor.",
    features: [
      "Lecture MP3 en mode karaoké (paroles synchronisées)",
      "Identification automatique & édition des tags ID3v2",
      "Gestion de playlists avec explorateur de fichiers",
      "Build Android via Capacitor",
    ],
    tech: ["Python", "PyQt", "Android"],
    shots: [],
  },
  {
    id: "videor", name: "Videor", repo: "videor", branch: "main", private: true,
    cat: "medias", kind: "Bureau Linux", year: "2025",
    tagline: "Lecture et gestion de votre bibliothèque vidéo.",
    pitch: "Une application desktop de lecture et de gestion de bibliothèque vidéo, écrite en Python.",
    features: [
      "Lecture vidéo",
      "Gestion de bibliothèque",
      "Application desktop Python",
    ],
    tech: ["Python", "PyQt"],
    shots: [],
  },
  {
    id: "tubor", name: "Tubor", repo: "tubor", branch: "main", private: true,
    cat: "medias", kind: "Bureau Linux · Web", year: "2025",
    tagline: "Une interface graphique élégante pour yt-dlp.",
    pitch: "Un front-end graphique intuitif pour exploiter yt-dlp sous Linux : téléchargements suivis en temps réel par WebSocket, prévisualisation, file d'attente et paramètres avancés. Backend FastAPI, interface React.",
    features: [
      "Interface graphique pour yt-dlp",
      "Téléchargements suivis en temps réel (WebSocket)",
      "Prévisualisation et file d'attente",
      "Backend FastAPI + interface React",
    ],
    tech: ["Python", "FastAPI", "React", "yt-dlp"],
    shots: ["assets/shots/tubor.png"],
  },
  {
    id: "librelector", name: "LibreLector", repo: "LibreLector", branch: "main", private: true,
    cat: "medias", kind: "Bureau Linux · Web", year: "2025", live: "https://librelector.netlify.app",
    tagline: "Lecteur d'EPUB qui lit vos livres à voix haute.",
    pitch: "Un lecteur de fichiers EPUB (et PDF, FB2, TXT) qui lit à voix haute via le moteur TTS Kokoro ou Web Speech, avec notes, marque-pages et bibliothèque. Décliné en desktop (Tauri) et en web.",
    features: [
      "Lecture EPUB, PDF, FB2, TXT",
      "Lecture à voix haute (TTS Kokoro & Web Speech)",
      "Notes, marque-pages et bibliothèque",
      "Versions desktop (Tauri) et web",
    ],
    tech: ["Python", "React", "Tauri", "TTS"],
    shots: [],
  },
  {
    id: "rssnews", name: "RssNews", repo: "rssnews", branch: "main", private: true,
    cat: "medias", kind: "Bureau Linux · Web", year: "2025", live: "https://rssreador.netlify.app",
    tagline: "Lecteur de flux RSS avec lecture vocale.",
    pitch: "Un agrégateur de flux RSS qui lit les articles à voix haute, disponible en desktop (PyQt) et en web (React + backend FastAPI).",
    features: [
      "Agrégation de flux RSS",
      "Lecture des articles à voix haute",
      "Versions desktop (PyQt) et web (React/FastAPI)",
    ],
    tech: ["Python", "React", "FastAPI", "TTS"],
    shots: [],
  },
  {
    id: "pdf-epubor", name: "PDF-Epubor", repo: "pdf-epubor", branch: "main", private: true,
    cat: "medias", kind: "Bureau Linux", year: "2025",
    tagline: "Convertir des PDF en EPUB propres et lisibles.",
    pitch: "Un outil desktop pour convertir des PDF en EPUB : extraction, nettoyage avancé du texte et reconstruction d'un EPUB lisible, avec aperçu en direct.",
    features: [
      "Conversion PDF → EPUB",
      "Nettoyage avancé du texte",
      "Aperçu en direct",
    ],
    tech: ["Python", "PyQt"],
    shots: [],
  },
  {
    id: "recordor", name: "Recordor", repo: "recordor", branch: "main", private: true,
    cat: "medias", kind: "Android", year: "2025",
    tagline: "Enregistreur d'écran pour tutos sur téléphone.",
    pitch: "Une app Android (Kotlin) d'enregistrement d'écran pensée pour réaliser des tutoriels sur téléphone, avec un service d'enregistrement en arrière-plan.",
    features: [
      "Enregistrement d'écran Android",
      "Service d'enregistrement en arrière-plan",
      "Pensé pour les tutoriels sur téléphone",
    ],
    tech: ["Kotlin", "Android"],
    shots: [],
  },

  // ───────────────────────── Création & écriture
  {
    id: "dessinator", name: "Dessinator", repo: "Dessinator", branch: "main", private: true,
    cat: "creation", kind: "Bureau Linux", year: "2025",
    tagline: "Un outil de dessin façon Paint, pour Linux.",
    pitch: "Un éditeur de dessin bitmap inspiré de Paint 95 : pinceau, formes, sélection, pipette, historique undo/redo et palette. Architecture modulaire en Python / PyQt.",
    features: [
      "Pinceau, formes, sélection, pipette",
      "Historique undo / redo",
      "Palette de couleurs",
      "Architecture modulaire PyQt",
    ],
    tech: ["Python", "PyQt"],
    shots: ["assets/shots/dessinator.png"],
  },
  {
    id: "macroeditor", name: "MacroEditor", repo: "MacroEditor", branch: "main", private: true,
    cat: "creation", kind: "Bureau Linux", year: "2025",
    tagline: "Éditeur de texte avec macros enregistrables à la volée.",
    pitch: "Un éditeur de texte graphique sous Linux dont la fonctionnalité phare est l'enregistrement et la relecture de macros directement depuis l'interface, plus la sélection en colonnes.",
    features: [
      "Enregistrement et relecture de macros à la volée",
      "Sélection en colonnes",
      "Éditeur de texte graphique Linux",
    ],
    tech: ["Python", "GTK", "Macros"],
    shots: ["assets/shots/macroeditor.gif"],
  },
  {
    id: "markor", name: "Markor", repo: "markor", branch: "main", private: true,
    cat: "creation", kind: "Bureau Linux", year: "2025",
    tagline: "Markdown → PDF, avec éditeur intégré.",
    pitch: "Un petit outil focalisé : transformer du Markdown en PDF, avec éditeur intégré et aperçu. Léger et sans superflu.",
    features: [
      "Conversion Markdown → PDF",
      "Éditeur intégré avec aperçu",
    ],
    tech: ["Python", "Markdown"],
    shots: [],
  },
  {
    id: "noteor", name: "Noteor", repo: "Noteor", branch: "main", private: true,
    cat: "creation", kind: "Bureau Linux · Web", year: "2025", live: "https://noteor.netlify.app",
    tagline: "Prise de notes textuelles et vocales.",
    pitch: "Une app de prise de notes textuelles et vocales : éditeur riche, enregistrement audio et webcam, vue calendrier et graphe de liens entre notes. Desktop (PyQt) et web (React), avec IA via OpenRouter.",
    features: [
      "Notes textuelles et vocales",
      "Enregistrement audio et webcam",
      "Vue calendrier et graphe de liens",
      "Versions desktop et web, IA OpenRouter",
    ],
    tech: ["Python", "React", "IA"],
    shots: [],
  },
  {
    id: "journalor", name: "Journalor", repo: "journalor", branch: "main", private: true,
    cat: "creation", kind: "Bureau Linux", year: "2025",
    tagline: "Journal intime chiffré avec transcription vocale.",
    pitch: "Un journal personnel desktop : entrées chiffrées, enregistrement vocal avec transcription locale (Whisper), recherche, statistiques et export. La confidentialité d'abord.",
    features: [
      "Entrées chiffrées",
      "Enregistrement vocal + transcription locale (Whisper)",
      "Recherche, statistiques et export",
    ],
    tech: ["Python", "PyQt", "Whisper", "Chiffrement"],
    shots: [],
  },

  // ───────────────────────── Système & réseau
  {
    id: "syscontrolor", name: "Syscontrolor", repo: "syscontrolor", branch: "main", private: true,
    cat: "systeme", kind: "Bureau Linux", year: "2025",
    tagline: "systemctl, mais avec une vraie interface graphique.",
    pitch: "Une interface graphique GTK pour piloter les services systemd : état des unités, démarrage / arrêt, constructeur de commandes et historique, avec élévation de privilèges sécurisée.",
    features: [
      "Gestion des services systemd (start / stop / statut)",
      "Constructeur de commandes",
      "Historique des actions",
      "Élévation de privilèges sécurisée",
    ],
    tech: ["Python", "GTK", "systemd"],
    shots: ["assets/shots/syscontrolor.png"],
  },
  {
    id: "dmesgviewor", name: "DmesgViewor", repo: "DmesgViewor", branch: "main", private: true,
    cat: "systeme", kind: "Bureau Linux", year: "2025",
    tagline: "Visualiseur dmesg avec filtres et timeline.",
    pitch: "Une app graphique Linux pour explorer le buffer noyau (dmesg) : affichage structuré, filtrage avancé, recherche, coloration, suivi temps réel, détection d'anomalies et export.",
    features: [
      "Lecture structurée du buffer noyau (dmesg)",
      "Filtrage avancé, recherche, coloration",
      "Suivi temps réel et détection d'anomalies",
      "Export des journaux",
    ],
    tech: ["Python", "PyQt", "Kernel"],
    shots: [],
  },
  {
    id: "nftor", name: "Nftor", repo: "nftor", branch: "main", private: true,
    cat: "systeme", kind: "Web", year: "2025",
    tagline: "Compteurs nftables en temps réel.",
    pitch: "Une visibilité en temps réel sur les compteurs nftables : streaming live par WebSocket, rétention historique et filtrage par chaîne. Backend FastAPI, front React.",
    features: [
      "Compteurs nftables en temps réel (WebSocket)",
      "Rétention historique",
      "Filtrage par chaîne",
      "Backend FastAPI + front React",
    ],
    tech: ["Python", "FastAPI", "React", "nftables"],
    shots: [],
  },
  {
    id: "networkor", name: "Networkor", repo: "networkor", branch: "main", private: true,
    cat: "systeme", kind: "Web", year: "2025",
    tagline: "Assistant networking en Go + React.",
    pitch: "Un assistant de gestion de contacts professionnels : score de santé des relations, graphe, génération de messages par IA et import de carnets. Backend Go performant, interface React.",
    features: [
      "Score de santé des relations",
      "Graphe des contacts",
      "Génération de messages par IA",
      "Import de carnets, backend Go",
    ],
    tech: ["Go", "React", "IA", "PostgreSQL"],
    shots: [],
  },
  {
    id: "findor", name: "Findor", repo: "findor", branch: "main", private: true,
    cat: "systeme", kind: "Web · Bureau", year: "2025",
    tagline: "Une interface graphique pour la commande find.",
    pitch: "Une interface graphique avancée pour la commande find de Linux : composer des recherches complexes sans mémoriser la syntaxe. Décliné en PyQt et en web (React + backend FastAPI).",
    features: [
      "Interface graphique pour la commande find",
      "Compose des recherches complexes sans syntaxe",
      "Versions PyQt et web (React / FastAPI)",
    ],
    tech: ["Python", "PyQt", "React"],
    shots: [],
  },
  {
    id: "swinux", name: "Swinux", repo: "swinux", branch: "main", private: true,
    cat: "systeme", kind: "Formation", year: "2025",
    tagline: "Programmes de formation Linux pour pros IT.",
    pitch: "Une plateforme dédiée à la conception et à la diffusion de programmes de formation Linux complets, pour les professionnels IT, administrateurs systèmes et développeurs qui veulent maîtriser le système.",
    features: [
      "Programmes de formation Linux complets",
      "Pour pros IT, sysadmins et développeurs",
    ],
    tech: ["Linux", "Formation"],
    shots: [],
  },

  // ───────────────────────── Langues & IA
  {
    id: "prononciator", name: "Prononciator", repo: "Prononciator", branch: "main", private: true,
    cat: "langues", kind: "Web · PWA", year: "2025", live: "https://prononciator.netlify.app",
    tagline: "Apprendre l'anglais grâce à l'IA.",
    pitch: "Une app d'apprentissage de l'anglais centrée sur la prononciation : conversation IA, exercices, vocabulaire avec répétition espacée (SRS) et reconnaissance vocale. Génération via OpenRouter.",
    features: [
      "Conversation IA en anglais",
      "Exercices et reconnaissance vocale",
      "Vocabulaire avec répétition espacée (SRS)",
      "Génération via OpenRouter",
    ],
    tech: ["React", "Vite", "IA", "Voix", "SRS"],
    shots: [],
  },
  {
    id: "libretrador", name: "LibreTrador", repo: "libretrador", branch: "main", private: true,
    cat: "langues", kind: "Bureau Linux", year: "2025",
    tagline: "Traducteur FR ↔ EN, 100 % hors-ligne.",
    pitch: "Traduction de textes et de fichiers entre l'anglais et le français, entièrement hors-ligne via Argos Translate ou Ollama : glossaire, sous-titres SRT, historique et synthèse vocale. Aucune connexion réseau après l'installation du modèle.",
    features: [
      "Traduction FR ↔ EN hors-ligne (Argos / Ollama)",
      "Glossaire et sous-titres SRT",
      "Historique et synthèse vocale",
      "Aucune connexion réseau requise",
    ],
    tech: ["Python", "PyQt", "Ollama", "Hors-ligne"],
    shots: [],
  },
  {
    id: "verifyor", name: "Verifyor", repo: "verifyor", branch: "main", private: true,
    cat: "langues", kind: "Web · Bureau", year: "2025",
    tagline: "Vérification forensique d'identités email.",
    pitch: "Vérification forensique d'identités email en temps réel : recoupement multi-fournisseurs, scoring de risque et génération de rapports. Service Node.js avec interface web.",
    features: [
      "Vérification d'identités email en temps réel",
      "Recoupement multi-fournisseurs",
      "Scoring de risque",
      "Génération de rapports",
    ],
    tech: ["Node.js", "JavaScript", "Forensic"],
    shots: [],
  },
  {
    id: "konnector", name: "Konnector", repo: "konnector", branch: "master", private: true,
    cat: "langues", kind: "Web", year: "2025",
    tagline: "Cartographiez votre réseau, trouvez les intros chaudes.",
    pitch: "Visualise vos contacts en graphe interactif (d3-force), détecte les chemins d'introduction vers vos cibles et importe vos connexions depuis LinkedIn, Google ou un CSV. IA Claude optionnelle pour les synthèses de contacts et les suggestions d'introduction.",
    features: [
      "Graphe de contacts interactif (d3-force)",
      "Détection des chemins d'introduction",
      "Import LinkedIn, Google Contacts, CSV",
      "Synthèses & suggestions d'intro via Claude (optionnel)",
    ],
    tech: ["React", "TypeScript", "d3", "IA"],
    shots: [],
  },
];

/* Mots-clés pour le classement heuristique des dépôts synchronisés (repli sans IA) */
export const CAT_KEYWORDS = {
  sante:    ["sant", "medic", "nutri", "secour", "urgen", "patho", "soin", "huile", "fodmap"],
  maison:   ["recett", "cuisin", "jardin", "potager", "theatr", "famille", "genealog", "maison"],
  data:     ["meteo", "weather", "bourse", "finan", "stock", "climat", "open-meteo"],
  medias:   ["video", "audio", "music", "mp3", "rss", "epub", "pdf", "karaok", "yt-dlp", "lecteur", "record", "ecran", "tube"],
  creation: ["dessin", "paint", "note", "journal", "markdown", "editor", "editeur", "macro", "ecritur"],
  systeme:  ["systemd", "dmesg", "nftables", "network", "find", "linux", "kernel", "admin", "gtk", "service"],
  langues:  ["anglais", "english", "tradu", "translat", "prononc", "verif", "email", "konnect", "reseau"],
};
